[package]
name = "dns-zonefile"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
regex = "1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"

[lib]
name = "dns_zonefile"
path = "src/lib.rs"
doctest = false
